import React, { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { FaFire } from 'react-icons/fa';
import Marketing from '../Marketing';
import Head from 'next/head';
const Trending = () => {
    const [serach,setSerach]=useState([])
    const[product,setProduct]=useState([])
   
    useEffect(()=>{
        fetch('http://localhost:5000/product')
        .then(res=>res.json())
        .then(data=>{
            setProduct(data)
           
        })
    },[])

    return (
        <div className='container'>
           <Head>
        <title>FERI Trending Product</title>
        <meta name="description" content="Generated by FERI Trending Product" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
              <div className='ms-auto w-25 pt-3'>
                
            
              
             
      </div>
           
                               <div className='container mt-5 mb-5 shadow bg-white p-2'>
                              

                               <h6>Trending Product <FaFire className='text-danger'/> </h6>
                               <div className="card-group">
            {
                product
                .filter((data)=>{
                 
                      if(data.title==="Trending"){
                        return data
                      }
                      // else if(data.category ? data.category.toLowerCase().includes(serach.toLowerCase()):""){
                      //   return data
                      // }
                    })
               
                
                
                .slice(0,6).map(products=>(
                    
                <>
                     
                         <div className="card" key={products.id}>
    <img src={products?.img} className="card-img-top" alt="..."/>
    <div class="card-body">
      <small className="card-title">{products?.name}</small>
    
    </div>
    <h6 className='fw-bold ps-2'>{products?.price}<span className='fs-3'>৳</span></h6>
    <div className="card-footer">
    <button className='btn btn-info w-100'><Link href={'/Product/'+ products?._id} key={products?._id}>Details</Link></button>
    </div>
  </div>
                       
                            </>))
            }
             </div>
            
             
                    </div>
        </div>
    );
};

export default Trending;