import Script from 'next/script'
import '../styles/globals.css'

import Nav from "./nav"
import Head from 'next/head'
import {SessionProvider} from "next-auth/react"
function MyApp({ Component, pageProps,session }) {

  return<>
  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
  <Nav/>
  <SessionProvider session={session}>

  <Component {...pageProps} />
  </SessionProvider>

  
  </>
  

}

export default MyApp
