import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

import Banner from "./Product/Banner"
import Product from "./Product/Product"
import Marketing from './Marketing'
export default function Home() {
  return (
    <div className="bg-light">
      <Head>
        <title>FERI E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>
       
    <Banner/>
    <Product/>
  
        </main>
    </div>
  )
}
